71 feature 291 récupération personnes disponible pour conversation
SchoodEIP/Schood-API pull request #72
Opened 2023-08-13 13:52 UTC by quentinmananes

2023-08-13 13:56 UTC, quentinmananes commented on src/__tests__/routes/adm/class/register.test.js
Change from 2.4.2 (needed)

2023-08-13 13:57 UTC, quentinmananes commented on src/config/db.default.js
Change from 2.4.2 (needed)

2023-08-13 13:57 UTC, quentinmananes commented on src/models/classes.js
Change from 2.4.2 (needed)

2023-08-13 13:57 UTC, quentinmananes commented on src/models/users.js
Change from 2.4.2 (needed)

2023-08-13 13:57 UTC, quentinmananes commented on src/package.json
Change from 2.4.2 (needed)

2023-08-13 13:57 UTC, quentinmananes commented on src/routes/adm/class/register.js
Change from 2.4.2 (needed)

2023-08-13 13:58 UTC, quentinmananes commented on src/routes/adm/csvRegisterUser.js
Change from 2.4.2 (needed)

2023-08-13 13:58 UTC, quentinmananes commented on src/routes/adm/register.js
Change from 2.4.2 (needed)

2023-08-13 13:58 UTC, quentinmananes commented on src/routes/adm/router.js
Change from 2.4.2 (needed)

2023-08-26 20:12 UTC, Exiels requested changes

2023-08-26 20:12 UTC, Exiels commented on src/routes/user/chat/getAvailableChatUsers.js
> +    const result = await Users.aggregate(agg)
Beware of what you get from the aggregation. Do not send things like password, firstConnexion, facility and email.

Lookup and unwind classes and role

2023-08-26 20:12 UTC, Exiels commented on src/swagger.yaml
> +                $ref: '#/components/schemas/internalServerError'
Change the response to correspond to what the modified aggregation send

2023-08-30 05:17 UTC, Exiels approved these changes

2023-08-30 05:25 UTC, merged